#!/usr/bin/bash

set -xe

WALL_PATH=~/.local/share/.wall

NEW_WALL=$1

if [ -z "$NEW_WALL" ]  || [ ! -f $NEW_WALL ]
then
    echo "error setting wallpaper: file doesn't exist"
    exit 1
fi

# unload old wallpaper
hyprctl hyprpaper unload $WALL_PATH

# copy new wallpaper to wallpaper path
cp $NEW_WALL $WALL_PATH

# load new wallpaper and reload hyprland
hyprctl hyprpaper preload $WALL_PATH
hyprctl hyprpaper wallpaper ,$WALL_PATH
hyprctl reload
